language: node_js
node_js:
- '7'
- '8'
cache:
  directories:
  - node_modules
before_script:
  - npm run travis
env:
  global:
    - BOT_API_KEY=xoxb-254057928980-lM14BqLKp4Be3t7Hkm2hknYr
    - BOT_NAME=travis
